# -*- coding: utf-8 -*-
"""Roberta-custom-model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cpfsgFwtfrr2kbElIzI3PF2gxRWeXr3_
"""

import pandas as pd
import numpy as np
data = pd.read_csv('/content/Twitter_Data.csv')
data["clean_text"].fillna("random", inplace=True)
data["category"].fillna(0.0, inplace=True)
data["category"] = data["category"].apply(np.int64)
data["category"] = data["category"].replace(1,2)
data["category"] = data["category"].replace(0,1)
data["category"] = data["category"].replace(-1,0)
print(data)

tweets = data["clean_text"].values.tolist()
classifiers = data["category"].values.tolist()

from transformers import RobertaTokenizerFast, TFRobertaForSequenceClassification, TFTrainer, TFTrainingArguments
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
tf.test.gpu_device_name()

tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base", num_labels=3)
print("------------------train and test splits --------------------------")
X_train, X_test, Y_train, Y_test = train_test_split(tweets, classifiers, test_size=0.2, random_state=0)

#
print("-------------------tokenizing------------------------------")
train_encodings = tokenizer(X_train, truncation=True, padding=True, return_tensors='np')
test_encodings = tokenizer(X_test, truncation=True, padding=True, return_tensors='np')
print(train_encodings)

model = TFRobertaForSequenceClassification.from_pretrained("roberta-base", num_labels=3)

train_labels = np.array(Y_train)
test_labels = np.array(Y_test)
opt = tf.keras.optimizers.Adam(5e-5)  # Transformers like lower learning rates
model.compile(optimizer=opt, metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

"""----------------------------Training happens here -----------------------------"""

model.fit(dict(train_encodings), train_labels,epochs=5)
model.save('/content/customRobertaModel')

print("model is trained")

# !zip -r /content/customRobertaModel.zip /content/customRobertaModel/
#
# from google.colab import files
# files.download("/content/customRobertaModel.zip")